export const USERS_ARE_FETCHING = 'USERS_ARE_FETCHING'
export const USERS_FETCHED = 'USERS_FETCHED'
export const USERS_FETCH_FAILED = 'USERS_FETCH_FAILED'

export const CHART_IS_UPDATING = 'CHART_IS_UPDATING'
export const CHART_UPDATED = 'CHART_UPDATED'
export const CHART_FAILED = 'CHART_FAILED'